///////////////////////////////////////////////////////////////////////////////
//
//	This file declares attribute accessor functions used by the driver.  The
//	primary use for this file is in the Attributes.cpp file which defines the
//	mappings between attribute IDs and their corresponding accessor functions.
//
#pragma once

#include "StdAfx.h"

ViStatus _VI_FUNC KtMAwg_get_GENERATION_SETTINGS_RESTRICTIONS(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_SERIAL_NUMBER(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_SYSTEM_ABOUT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_SYSTEM_GC_TIMING_OPTIMIZATION_ENABLED(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_SYSTEM_GC_TIMING_OPTIMIZATION_ENABLED(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_SYSTEM_IDENTIFY_ENABLED(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_SYSTEM_IDENTIFY_ENABLED(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_SYSTEM_INSTANCE_ID(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_SYSTEM_OPTIONS(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_SYSTEM_TIMEOUT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_SYSTEM_TIMEOUT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_LICENSING_HOST_IDENTIFIER(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_LICENSING_INSTALLED_LICENSES(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_CALIBRATION_ADJUSTMENT_INFORMATION(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_CALIBRATION_DUE_DATE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_CALIBRATION_INSTRUMENT_IDENTIFIER(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_CALIBRATION_STATUS(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_CALIBRATION_VERIFICATION_INFORMATION(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_MODULE_COUNT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MODULE_INSTRUMENT_CAPABILITY(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_MODULE_MAXIMUM_RECORDED_TEMPERATURE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MODULE_OPTIONS(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_MODULE_SERIAL_NUMBER(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_MODULE_SLOT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MODULE_TEMPERATURE(ViSession Vi, ViConstString RepCapIdentifier, ViReal64* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MODULE_CALIBRATION_ADJUSTMENT_INFORMATION(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_MODULE_CALIBRATION_DUE_DATE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_MODULE_CALIBRATION_STATUS(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MODULE_CALIBRATION_VERIFICATION_INFORMATION(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_NONVOLATILE_ASSET_NUMBER(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_set_NONVOLATILE_ASSET_NUMBER(ViSession Vi, ViConstString RepCapIdentifier, ViConstString AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_NONVOLATILE_CAL_DUE_REMINDER(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_NONVOLATILE_CAL_DUE_REMINDER(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_NONVOLATILE_ENABLE_INSTRUMENT_CAL_WARNINGS(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_NONVOLATILE_ENABLE_INSTRUMENT_CAL_WARNINGS(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_NONVOLATILE_ENABLE_MODULE_CAL_WARNINGS(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_NONVOLATILE_ENABLE_MODULE_CAL_WARNINGS(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_NONVOLATILE_ENABLE_PERIODIC_CAL(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_NONVOLATILE_ENABLE_PERIODIC_CAL(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_NONVOLATILE_INSTRUMENT_CAL_INTERVAL(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_NONVOLATILE_INSTRUMENT_CAL_INTERVAL(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_NONVOLATILE_MODULE_CAL_INTERVAL(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_NONVOLATILE_MODULE_CAL_INTERVAL(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_NONVOLATILE_PASSPHRASE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_set_NONVOLATILE_PASSPHRASE(ViSession Vi, ViConstString RepCapIdentifier, ViConstString AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_NONVOLATILE_SYSTEM_IDENTIFICATION(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_set_NONVOLATILE_SYSTEM_IDENTIFICATION(ViSession Vi, ViConstString RepCapIdentifier, ViConstString AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_ASSETCHANNEL_COUNT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_PEERTOPEERPORT_COUNT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_ACTIVE_PEERTOPEERPORT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_set_ACTIVE_PEERTOPEERPORT(ViSession Vi, ViConstString RepCapIdentifier, ViConstString AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_DEVICE_SYNC_CLOCK_RATE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_DEVICE_SYNC_CLOCK_RATE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_DEVICE_SYNC_CLOCK_SOURCE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_set_DEVICE_SYNC_CLOCK_SOURCE(ViSession Vi, ViConstString RepCapIdentifier, ViConstString AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_DEVICE_SYNC_GROUP_MASK(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_DEVICE_SYNC_GROUP_MASK(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_DEVICE_SYNC_GROUP_SIGNAL(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_DEVICE_SYNC_GROUP_SIGNAL(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_DEVICE_SYNC_ROLE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_DEVICE_SYNC_ROLE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_DEVICE_SYNC_SLAVE_SIGNAL(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_DEVICE_SYNC_SLAVE_SIGNAL(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_DEVICE_SYNC_STATE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_DEVICE_SYNC_IS_ALIGNMENT_VALID(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_DEVICE_SYNC_SYNC_CHANNELS(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_set_DEVICE_SYNC_SYNC_CHANNELS(ViSession Vi, ViConstString RepCapIdentifier, ViConstString AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_ARB_NUMBER_WAVEFORMS(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_ARB_NUMBER_SEQUENCES(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_SEQUENCETRIGGER_MAX_COUNT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_SEQUENCETRIGGER_COUNT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MARKER_COUNT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MARKER_MAX_COUNT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_EXTERNAL_COUNT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_EXTERNAL_INPUT_SLOPE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_EXTERNAL_INPUT_SLOPE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_EXTERNAL_OUTPUT_POLARITY(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_EXTERNAL_OUTPUT_POLARITY(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_EXTERNAL_THRESHOLD(ViSession Vi, ViConstString RepCapIdentifier, ViReal64* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_EXTERNAL_THRESHOLD(ViSession Vi, ViConstString RepCapIdentifier, ViReal64 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_TRIGGER_BUS_LINE_COUNT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_TRIGGER_BUS_LINE_INPUT_SLOPE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_TRIGGER_BUS_LINE_INPUT_SLOPE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_TRIGGER_BUS_LINE_OUTPUT_POLARITY(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_TRIGGER_BUS_LINE_OUTPUT_POLARITY(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_TRIGGER_BUS_LINE_CAPABILITY(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_REF_CLOCK_IS_PHASE_LOCKED(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_SPECIFIC_DRIVER_DESCRIPTION(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_SPECIFIC_DRIVER_PREFIX(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_SPECIFIC_DRIVER_VENDOR(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_SPECIFIC_DRIVER_REVISION(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_RANGE_CHECK(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_RANGE_CHECK(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_QUERY_INSTRUMENT_STATUS(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_QUERY_INSTRUMENT_STATUS(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_CACHE(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_CACHE(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_SIMULATE(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_SIMULATE(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_RECORD_COERCIONS(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_RECORD_COERCIONS(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_INTERCHANGE_CHECK(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_INTERCHANGE_CHECK(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_LOGICAL_NAME(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_IO_RESOURCE_DESCRIPTOR(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_DRIVER_SETUP(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_GROUP_CAPABILITIES(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_SUPPORTED_INSTRUMENT_MODELS(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_INSTRUMENT_FIRMWARE_REVISION(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_INSTRUMENT_MANUFACTURER(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_INSTRUMENT_MODEL(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_get_ARB_GAIN(ViSession Vi, ViConstString RepCapIdentifier, ViReal64* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_ARB_GAIN(ViSession Vi, ViConstString RepCapIdentifier, ViReal64 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_ARB_OFFSET(ViSession Vi, ViConstString RepCapIdentifier, ViReal64* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_ARB_OFFSET(ViSession Vi, ViConstString RepCapIdentifier, ViReal64 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_ARB_SAMPLE_RATE(ViSession Vi, ViConstString RepCapIdentifier, ViReal64* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_ARB_SAMPLE_RATE(ViSession Vi, ViConstString RepCapIdentifier, ViReal64 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_ARB_WAVEFORM_HANDLE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_ARB_WAVEFORM_HANDLE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MAX_NUM_WAVEFORMS(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_WAVEFORM_QUANTUM(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MAX_WAVEFORM_SIZE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MAX_WAVEFORM_SIZE64(ViSession Vi, ViConstString RepCapIdentifier, ViInt64* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MIN_WAVEFORM_SIZE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MIN_WAVEFORM_SIZE64(ViSession Vi, ViConstString RepCapIdentifier, ViInt64* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_BINARY_ALIGNMENT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_SAMPLE_BIT_RESOLUTION(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_OUTPUT_DATA_MASK(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_ARB_SEQUENCE_HANDLE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_ARB_SEQUENCE_HANDLE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MAX_SEQUENCE_LENGTH(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MIN_SEQUENCE_LENGTH(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MAX_LOOP_COUNT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MAX_NUM_SEQUENCES(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_MAX_SEQUENCE_DEPTH(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_CHANNEL_COUNT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_OUTPUT_ENABLED(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_OUTPUT_ENABLED(ViSession Vi, ViConstString RepCapIdentifier, ViBoolean AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_OUTPUT_IMPEDANCE(ViSession Vi, ViConstString RepCapIdentifier, ViReal64* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_OUTPUT_IMPEDANCE(ViSession Vi, ViConstString RepCapIdentifier, ViReal64 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_OPERATION_MODE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_OPERATION_MODE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_OUTPUT_MODE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_OUTPUT_MODE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_REF_CLOCK_SOURCE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_REF_CLOCK_SOURCE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_TERMINAL_CONFIGURATION(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_TERMINAL_CONFIGURATION(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_BURST_COUNT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_BURST_COUNT(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_TRIGGER_SOURCE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_TRIGGER_SOURCE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_START_TRIGGER_DELAY(ViSession Vi, ViConstString RepCapIdentifier, ViReal64* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_START_TRIGGER_DELAY(ViSession Vi, ViConstString RepCapIdentifier, ViReal64 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_START_TRIGGER_SLOPE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_START_TRIGGER_SLOPE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_START_TRIGGER_SOURCE(ViSession Vi, ViConstString RepCapIdentifier, ViInt32 AttributeValueBufferSize, ViChar AttributeValue[]);
ViStatus _VI_FUNC KtMAwg_set_START_TRIGGER_SOURCE(ViSession Vi, ViConstString RepCapIdentifier, ViConstString AttributeValue);
ViStatus _VI_FUNC KtMAwg_get_START_TRIGGER_THRESHOLD(ViSession Vi, ViConstString RepCapIdentifier, ViReal64* AttributeValue);
ViStatus _VI_FUNC KtMAwg_set_START_TRIGGER_THRESHOLD(ViSession Vi, ViConstString RepCapIdentifier, ViReal64 AttributeValue);

